In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("open/data/train.csv")
df.head()

,row_id,season,game_month,game_dayofweek,inning,top_bottom,game_type,balls_before,strikes_before,outs_before,...,asof_pitcher_prev3_game_middle_rate,asof_pitcher_prev5_game_middle_rate,asof_batter_n,asof_batter_success_rate,asof_batter_middle_rate,asof_pitcher_pitchmix_n,asof_pitcher_fastball_rate,asof_pitcher_breaking_rate,asof_pitcher_offspeed_rate,control_success
0,TRAIN_0000001,2019,3,5,1,T,R,0,0,0,...,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,0
1,TRAIN_0000002,2019,3,5,1,T,R,0,0,0,...,NaN,NaN,0,NaN,NaN,1,1.0,0.0,0.0,0
2,TRAIN_0000003,2019,3,5,1,T,R,1,0,0,...,NaN,NaN,1,0.0,0.0,2,1.0,0.0,0.0,0
3,TRAIN_0000004,2019,3,5,1,T,R,0,0,2,...,NaN,NaN,0,NaN,NaN,3,1.0,0.0,0.0,1
4,TRAIN_0000005,2019,3,5,1,T,R,0,1,2,...,NaN,NaN,1,1.0,0.0,4,1.0,0.0,0.0,1

In [3]:
df.select_dtypes(include='object').columns

Index(['row_id', 'top_bottom', 'game_type', 'base_state'], dtype='object')

In [4]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
le1 = LabelEncoder()
df['top_bottom'] = le1.fit_transform(df['top_bottom'])

le2 = LabelEncoder()
df['game_type'] = le2.fit_transform(df['game_type'])

le3 = LabelEncoder()
df['base_state'] = le3.fit_transform(df['base_state'])

In [6]:
group_mean = df.groupby('pitcher_id')['asof_pitcher_prev3_game_middle_rate'].transform('mean')

df['asof_pitcher_prev3_game_middle_rate'] = df['asof_pitcher_prev3_game_middle_rate'].fillna(group_mean)

In [7]:
df.loc[:, df.isna().any()].isna().sum()

asof_pitcher_success_rate                 792
asof_pitcher_reverse_rate                 792
asof_pitcher_middle_rate                  792
asof_pitcher_ball_rate                    792
asof_pitcher_strike_rate                  792
asof_pitcher_prev1_game_success_rate    29185
asof_pitcher_prev3_game_success_rate    29185
asof_pitcher_prev5_game_success_rate    29185
asof_pitcher_prev1_game_middle_rate     29185
asof_pitcher_prev3_game_middle_rate      1372
asof_pitcher_prev5_game_middle_rate     29185
asof_batter_success_rate                  830
asof_batter_middle_rate                   830
asof_pitcher_fastball_rate                792
asof_pitcher_breaking_rate                792
asof_pitcher_offspeed_rate                792
dtype: int64

In [8]:
pitcher_cols = [
    'asof_pitcher_success_rate',
    'asof_pitcher_reverse_rate',
    'asof_pitcher_middle_rate',
    'asof_pitcher_ball_rate',
    'asof_pitcher_strike_rate',
    'asof_pitcher_prev1_game_success_rate',
    'asof_pitcher_prev3_game_success_rate',
    'asof_pitcher_prev5_game_success_rate',
    'asof_pitcher_prev1_game_middle_rate',
    'asof_pitcher_prev3_game_middle_rate',
    'asof_pitcher_prev5_game_middle_rate',
    'asof_pitcher_fastball_rate',
    'asof_pitcher_breaking_rate',
    'asof_pitcher_offspeed_rate'
]

for col in pitcher_cols:
    pitcher_mean = df.groupby('pitcher_id')[col].transform('mean')
    
    global_mean = df[col].mean()
    
    df[col] = df[col].fillna(pitcher_mean).fillna(global_mean)

In [9]:
batter_cols = [
    'asof_batter_success_rate',
    'asof_batter_middle_rate'
]

for col in batter_cols:
    batter_mean = df.groupby('batter_id')[col].transform('mean')
    
    global_mean = df[col].mean()
    
    df[col] = df[col].fillna(batter_mean).fillna(global_mean)

In [10]:
df.iloc[:, 1:]

,season,game_month,game_dayofweek,inning,top_bottom,game_type,balls_before,strikes_before,outs_before,run_top_before,...,asof_pitcher_prev3_game_middle_rate,asof_pitcher_prev5_game_middle_rate,asof_batter_n,asof_batter_success_rate,asof_batter_middle_rate,asof_pitcher_pitchmix_n,asof_pitcher_fastball_rate,asof_pitcher_breaking_rate,asof_pitcher_offspeed_rate,control_success
0,2019,3,5,1,1,1,0,0,0,0,...,0.183259,0.182014,0,0.473526,0.153624,0,0.574206,0.206932,0.218861,0
1,2019,3,5,1,1,1,0,0,0,0,...,0.183259,0.182014,0,0.480074,0.159909,1,1.000000,0.000000,0.000000,0
2,2019,3,5,1,1,1,1,0,0,0,...,0.183259,0.182014,1,0.000000,0.000000,2,1.000000,0.000000,0.000000,0
3,2019,3,5,1,1,1,0,0,2,0,...,0.183259,0.182014,0,0.501707,0.144566,3,1.000000,0.000000,0.000000,1
4,2019,3,5,1,1,1,0,1,2,0,...,0.183259,0.182014,1,1.000000,0.000000,4,1.000000,0.000000,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475087,2024,10,5,10,0,0,3,0,1,6,...,0.107143,0.138889,2639,0.569913,0.130731,176,0.857955,0.130682,0.011364,1
1475088,2024,10,5,10,0,0,0,0,1,6,...,0.107143,0.138889,2710,0.525461,0.149815,177,0.858757,0.129944,0.011299,0
1475089,2024,10,5,10,0,0,0,1,1,6,...,0.107143,0.138889,2711,0.525267,0.150129,178,0.859551,0.129213,0.011236,1
1475090,2024,10,5,10,0,0,0,0,2,6,...,0.107143,0.138889,1021,0.625857,0.131244,179,0.860335,0.128492,0.011173,1
1475091,2024,10,5,10,0,0,1,0,2,6,...,0.107143,0.138889,1022,0.626223,0.131115,180,0.861111,0.127778,0.011111,1

In [11]:
sc = StandardScaler()
scaled_df = df.iloc[:, 1:]
transform_df = pd.DataFrame(sc.fit_transform(scaled_df), columns=scaled_df.columns)
df.loc[:, scaled_df.columns] = transform_df

/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.48248882 -1.48248882 -1.48248882 ...  1.44864164  1.44864164
  1.44864164]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.9029015  -1.9029015  -1.9029015  ...  1.72797955  1.72797955
  1.72797955]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.86072988 0.86072988 0.86072988 ... 0.86072988 0.86072988 0.86072988]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.52220647 -1.52220647 -1.52220647 ...  1.93215403  1.93215403
  1.93215403]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.97951147  0.97951147  0.97951147 ... -1.02091709 -1.02091709
 -1.02091709]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.35003068  0.35003068  0.35003068 ... -2.85689245 -2.85689245
 -2.85689245]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.92650253 -0.92650253  0.10470003 ... -0.92650253 -0.92650253
  0.10470003]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.0573196  -1.0573196  -1.0573196  ...  0.15538222 -1.0573196
 -1.0573196 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.20166451 -1.20166451 -1.20166451 ...  0.02273506  1.24713463
  1.24713463]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.87771221 -0.87771221 -0.87771221 ...  1.18115004  1.18115004
  1.18115004]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8520308  -0.8520308  -0.8520308  ...  0.59391058  0.59391058
  0.59391058]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.09204492 -1.09204492 -1.09204492 ...  1.12986933  1.12986933
  1.12986933]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.05788895  0.05788895  0.05788895 ... -0.51861143 -0.51861143
 -0.51861143]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.01729942 -0.01729942 -0.01729942 ...  0.55832353  0.55832353
  0.55832353]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.73436778  1.36171551  1.36171551 ...  1.36171551  1.36171551
  1.36171551]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.52609673 -0.52609673 -0.52609673 ...  1.90079113  1.90079113
  1.90079113]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.3544784  -0.3544784  -0.3544784  ...  2.82104634  2.82104634
  2.82104634]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.81416941  0.38532759  0.38532759 ...  2.78432159  2.78432159
  2.78432159]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.83534316 -0.88117901 -0.88117901 ... -2.16857063 -2.16857063
 -2.16857063]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.63043921 -1.63043921 -1.63043921 ...  1.54436896  1.54436896
  1.54436896]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.12566897 -0.99659263 -0.99659263 ...  1.12170694  1.48480954
  1.48480954]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.69353744 -1.69353744 -1.69353744 ...  0.59048001  0.59048001
  0.59048001]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.94484549 -1.05837411 -1.05837411 ... -1.05837411  0.94484549
  0.94484549]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.11461279 -0.11461279 -0.11461279 ...  1.58910221  1.58910221
  1.58910221]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.1355477 -1.1355477 -1.1355477 ... -1.1355477 -1.1355477 -1.1355477]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.98933513 -0.98896339 -0.98859164 ... -0.92316441 -0.92279267
 -0.92242092]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.07274632 -1.07274632 -1.07241835 ... -0.18361426 -0.73788692
 -0.73755895]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.98933513 -0.98896339 -0.98859164 ... -0.92316441 -0.92279267
 -0.92242092]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df
/var/folders/_k/9pcm610n0sb_j9n64tc8zgcw0000gn/T/ipykernel_38340/509390629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.0487173  -1.0487173  -1.0487173  ...  0.95354583  0.95354583
  0.95354583]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, scaled_df.columns] = transform_df

In [12]:
df.head()

,row_id,season,game_month,game_dayofweek,inning,top_bottom,game_type,balls_before,strikes_before,outs_before,...,asof_pitcher_prev3_game_middle_rate,asof_pitcher_prev5_game_middle_rate,asof_batter_n,asof_batter_success_rate,asof_batter_middle_rate,asof_pitcher_pitchmix_n,asof_pitcher_fastball_rate,asof_pitcher_breaking_rate,asof_pitcher_offspeed_rate,control_success
0,TRAIN_0000001,-1.482489,-1.902902,0.86073,-1.522206,0.979511,0.350031,-0.926503,-1.057320,-1.201665,...,0.607511,0.700898,-1.072746,-1.281371,0.481995,-0.989335,0.199610,-0.759987,0.576546,-1.048717
1,TRAIN_0000002,-1.482489,-1.902902,0.86073,-1.522206,0.979511,0.350031,-0.926503,-1.057320,-1.201665,...,0.607511,0.700898,-1.072746,-1.154675,0.712819,-0.988963,4.494102,-2.670147,-1.441092,-1.048717
2,TRAIN_0000003,-1.482489,-1.902902,0.86073,-1.522206,0.979511,0.350031,0.104700,-1.057320,-1.201665,...,0.607511,0.700898,-1.072418,-10.444055,-5.160734,-0.988592,4.494102,-2.670147,-1.441092,-1.048717
3,TRAIN_0000004,-1.482489,-1.902902,0.86073,-1.522206,0.979511,0.350031,-0.926503,-1.057320,1.247135,...,0.607511,0.700898,-1.072746,-0.736077,0.149255,-0.988220,4.494102,-2.670147,-1.441092,0.953546
4,TRAIN_0000005,-1.482489,-1.902902,0.86073,-1.522206,0.979511,0.350031,-0.926503,0.155382,1.247135,...,0.607511,0.700898,-1.072418,8.905844,-5.160734,-0.987848,4.494102,-2.670147,-1.441092,0.953546

In [13]:
import numpy as np

corr = df.iloc[:, 1:].corr().abs()

upper_mask = np.triu(np.ones(corr.shape), k=1).astype(bool)
upper_corr = corr.where(upper_mask)

high_corr_pairs = (
    upper_corr.stack()
    .reset_index()
    .rename(columns={'level_0': 'Feature_1', 'level_1': 'Feature_2', 0: 'Correlation'})
)

high_corr_pairs = high_corr_pairs[high_corr_pairs['Correlation'] >= 0.5]

In [14]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_rows', 50)

sorted_high_corr = high_corr_pairs.sort_values(by='Correlation', ascending=False)

print(sorted_high_corr.head(20))

                                 Feature_1                             Feature_2  Correlation
952                         asof_pitcher_n               asof_pitcher_pitchmix_n     1.000000
722                    home_win_expectancy                   away_win_expectancy     1.000000
663                         num_runners_on                            base_state     0.940438
570                           runner_on_1b                            base_state     0.918907
505                        score_diff_home                   away_win_expectancy     0.904791
504                        score_diff_home                   home_win_expectancy     0.904789
1050  asof_pitcher_prev3_game_success_rate  asof_pitcher_prev5_game_success_rate     0.883887
1083   asof_pitcher_prev3_game_middle_rate   asof_pitcher_prev5_game_middle_rate     0.847770
957              asof_pitcher_success_rate             asof_pitcher_reverse_rate     0.809914
388                         run_top_before                      run_total_before     0.804202
425                         run_bot_before                      run_total_before     0.779722
1008                asof_pitcher_ball_rate              asof_pitcher_strike_rate     0.773519
569                           runner_on_1b                        num_runners_on     0.745711
601                           runner_on_2b                        num_runners_on     0.705064
1037  asof_pitcher_prev1_game_success_rate  asof_pitcher_prev3_game_success_rate     0.664168
963              asof_pitcher_success_rate  asof_pitcher_prev5_game_success_rate     0.642992
389                         run_top_before                       score_diff_home     0.636760
145                                 inning                      run_total_before     0.617860
1073   asof_pitcher_prev1_game_middle_rate   asof_pitcher_prev3_game_middle_rate     0.596569
632                           runner_on_3b                        num_runners_on     0.595084